# Facebook metrics Data Set - Predicting Number of Comments of Facebook Posts

**To be completed INDIVIDUALLY and due on April 14 at 11:59pm.**

In this assignment, we will work on Facebook posts. The goal is to determine the number of comments a post will receive. Being able to predict the number of comments of a post can be viewed as predicting the impact a post will have, which makes this task quite challenging and interesting. You can find the dataset and details about it [here](https://archive.ics.uci.edu/ml/datasets/Facebook+metrics#) and [here](https://ac.els-cdn.com/S0148296316000813/1-s2.0-S0148296316000813-main.pdf?_tid=1944e5a8-e211-4dbc-bdd6-b233e4df6465&acdnat=1522453539_a59ca4034d01f4654986e45e18e79883). 

The data are stored in a .csv file and each row of the dataset corresponds to a distinct post (data instance). You will evaluate the performance of linear regression on the task of predicting the number of comments of a post.

Relevant Papers/citations: _Prédictions d’activité dans les réseaux sociaux en ligne_ (F. Kawala, A. Douzal-Chouakria, E. Gaussier, E. Dimert), In Actes de la Conférence sur les Modèles et l′Analyse des Réseaux : Approches Mathématiques et Informatique (MARAMI), pp. 16, 2013.

### Task 1

As learned in class most algorithms can only handle numeric values. However, in the given dataset you can see that the values of column 'Type' are categorical. Your first task is to prepare your dataset for linear regression and transform this column into numerical values. Note that creating a mapping that replaces the type field with a single number (e.g. Photo -> 1, Status ->2, Link ->3,...), will not be helpful here since the types are not ordered. Instead, use the "indicator vector" representation discussed in class. 
**(2 pt)**

In [1]:
import pandas as pd

df = pd.read_csv("C:\software\cs 506\cs506-spring2018-hw4-jweixuan\Facebook_metrics\dataset_Facebook.csv")

In [34]:
import numpy as np
df9 = pd.read_csv("C:\software\cs 506\cs506-spring2018-hw4-jweixuan\Facebook_metrics\dataset_Facebook.csv",sep = ';').fillna(0)

Y = df9.comment

df9 = df9.drop('comment',axis = 1)
Y = np.array(Y)

df9 = pd.get_dummies(data = df9, columns = ['Type'])
df9 = df9.drop("Total Interactions",1)
X = np.array(df9)
df9

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,like,share,Type_Link,Type_Photo,Type_Status,Type_Video
0,139441,2,12,4,3,0,2752,5091,178,109,159,3078,1640,119,79,17,0,1,0,0
1,139441,2,12,3,10,0,10460,19057,1457,1361,1674,11710,6112,1108,130,29,0,0,1,0
2,139441,3,12,3,3,0,2413,4373,177,113,154,2812,1503,132,66,14,0,1,0,0
3,139441,2,12,2,10,1,50128,87991,2211,790,1119,61027,32048,1386,1572,147,0,1,0,0
4,139441,2,12,2,3,0,7244,13594,671,410,580,6228,3200,396,325,49,0,1,0,0
5,139441,2,12,1,9,0,10472,20849,1191,1073,1389,16034,7852,1016,152,33,0,0,1,0
6,139441,3,12,1,3,1,11692,19479,481,265,364,15432,9328,379,249,27,0,1,0,0
7,139441,3,12,7,9,1,13720,24137,537,232,305,19728,11056,422,325,14,0,1,0,0
8,139441,2,12,7,3,0,11844,22538,1530,1407,1692,15220,7912,1250,161,31,0,0,1,0
9,139441,3,12,6,10,0,4694,8668,280,183,250,4309,2324,199,113,26,0,1,0,0
10,139441,2,12,5,10,0,21744,42334,4258,4100,4540,37849,18952,3798,233,19,0,0,1,0
11,139441,2,12,5,10,0,3112,5590,208,127,145,3887,2174,165,88,18,0,1,0,0
12,139441,2,12,5,10,0,2847,5133,193,115,133,3779,2072,152,90,14,0,1,0,0
13,139441,2,12,5,3,0,2549,4896,249,134,168,3631,1917,183,137,10,0,1,0,0
14,138414,2,12,4,5,1,22784,39941,887,337,417,34415,19312,684,577,20,0,1,0,0
15,138414,2,12,3,10,0,10060,19680,1264,1209,1425,17272,8548,1162,86,18,0,0,1,0
16,138414,3,12,3,3,0,1722,2981,163,123,148,1868,1050,123,40,12,0,1,0,0
17,138414,1,12,2,12,1,53264,111785,1706,1103,1655,92512,39776,1307,678,20,0,1,0,0
18,138414,3,12,2,3,0,3930,7509,130,86,112,5009,2410,101,54,17,0,0,1,0
19,138414,3,12,1,11,0,1591,2825,121,88,111,2116,1161,100,34,8,0,1,0,0
20,138414,2,12,1,3,0,2848,5066,200,142,184,3561,1963,157,66,12,0,1,0,0
21,138414,1,12,7,10,0,1384,2467,15,15,20,2196,1172,15,0,0,0,1,0,0
22,138414,1,12,7,10,0,3454,6853,118,104,130,6282,3100,106,16,2,1,0,0,0
23,138414,3,12,7,3,0,2723,4888,176,118,143,2964,1621,143,72,24,0,1,0,0
24,138414,2,12,6,10,0,8488,15294,1341,1270,1489,9684,5244,995,99,19,0,0,1,0
25,138458,2,12,6,3,0,8284,15104,1521,1462,1711,10266,5372,1200,88,18,0,0,1,0
26,138458,2,12,5,11,0,19552,34143,2806,2531,3420,17748,9824,1779,412,72,0,0,1,0
27,138458,3,12,5,3,0,2478,4306,212,124,149,2612,1443,166,100,17,0,1,0,0
28,138895,2,12,5,3,0,9560,18264,973,559,885,9217,4748,621,523,63,0,1,0,0
29,138895,1,12,4,11,1,36208,61262,1141,1068,1728,30131,14112,559,143,13,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,91437,1,2,3,13,0,9356,14986,448,381,505,13919,8460,392,114,13,1,0,0,0
471,91330,3,2,3,3,0,7732,13264,1066,1002,1336,8753,4880,570,160,57,0,1,0,0
472,91223,1,2,2,13,0,5240,8893,857,837,1020,7420,4232,466,46,15,0,1,0,0
473,91116,3,2,2,4,1,7132,12060,1004,944,1226,8294,4736,576,136,42,0,1,0,0
474,91009,1,2,1,12,0,21928,39641,1512,1479,1837,6338,3672,497,73,13,0,1,0,0
475,86909,3,1,6,16,1,5754,9238,1179,1143,1452,6101,3546,420,65,19,0,1,0,0
476,86909,1,1,6,10,1,37088,10966,2728,2288,3183,66311,34352,2021,579,47,0,1,0,0
477,86909,1,1,6,4,0,39600,7927,572,496,581,12522,8176,167,101,5,1,0,0,0
478,86909,3,1,5,13,0,5536,8745,1141,1099,1461,5225,3098,483,74,31,0,1,0,0
479,86909,3,1,5,4,0,6056,10325,1117,1078,1427,6823,3788,487,84,36,0,1,0,0
480,86909,2,1,4,11,0,11484,20696,1762,1635,2741,8774,5124,722,360,99,0,1,0,0
481,86491,1,1,4,4,1,4938,7910,66,63,70,6625,3804,59,5,2,1,0,0,0
482,86491,3,1,3,10,0,66784,9456,2969,2833,3645,17809,11328,801,187,36,0,1,0,0
483,86491,2,1,3,3,0,5526,8779,1096,1058,1399,5732,3412,453,69,26,0,1,0,0
484,86491,3,1,2,7,0,5040,8367,1062,1023,1348,5485,3068,437,82,24,0,1,0,0
485,86491,1,1,2,2,0,5168,8371,66,59,71,7041,3996,58,12,2,1,0,0,0
486,85979,3,1,1,12,0,5034,8030,1020,993,1243,5340,3094,440,56,25,0,1,0,0
487,85979,3,1,1,2,0,4908,7491,957,937,1153,4642,2842,393,44,21,0,1,0,0
488,85979,3,1,7,10,0,9700,17442,1407,1271,2007,8872,4876,660,277,80,0,1,0,0
489,85979,3,1,7,2,0,4800,7754,975,938,1278,4932,2820,432,74,28,0,1,0,0
490,85979,3,1,6,11,0,5280,8703,951,911,1237,5757,3300,431,79,30,0,1,0,0
491,85979,3,1,6,3,1,6184,10228,956,901,1140,6085,3502,437,105,46,0,1,0,0
492,85979,1,1,5,11,0,45920,5808,753,655,763,15766,10720,220,128,9,1,0,0,0
493,85093,3,1,1,2,0,8412,13960,1179,1111,1632,8632,5348,699,185,55,0,1,0,0
494,85093,3,1,7,10,0,5400,9218,810,756,1003,5654,3230,422,125,41,0,1,0,0
495,85093,3,1,7,2,0,4684,7536,733,708,985,4750,2876,392,53,26,0,1,0,0
496,81370,2,1,5,8,0,3480,6229,537,508,687,3961,2104,301,53,22,0,1,0,0
497,81370,1,1,5,2,0,3778,7216,625,572,795,4742,2388,363,93,18,0,1,0,0
498,81370,3,1,4,11,0,4156,7564,626,574,832,4534,2452,370,91,38,0,1,0,0
499,81370,2,1,4,4,0,4188,7292,564,524,743,3861,2200,316,91,28,0,1,0,0

### Task 2

Now your dataset is ready for linear regression. To familiarize yourself with this task, here simply use the following [package](http://www.statsmodels.org/dev/regression.html) to perform regression on the dataset. The dependent variable should be the column 'comment' and the remaining columns of your dataset should be the independent variables. Split your dataset into 80% and 20% for training and testing, respectively. Report the linear model's summary as shown [here](https://www.statsmodels.org/stable/index.html) by using the .summary() function after fitting your model and compute the error of your prediction using the [mean squared error (MSE)](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html).  **(2 pt)**

In [20]:
import numpy as np
import statsmodels.api as sm
from pandas.core import datetools
import sklearn.model_selection as model_selection

#mod = sm.OLS(df2.comment, df3.Paid)

In [35]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(X, Y, test_size=0.2, random_state=0)

est = sm.OLS(y_train,x_train)

est1=est.fit()

est1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.813
Model:                            OLS   Adj. R-squared:                  0.804
Method:                 Least Squares   F-statistic:                     87.02
Date:                Fri, 13 Apr 2018   Prob (F-statistic):          1.65e-125
Time:                        20:13:11   Log-Likelihood:                -1490.3
No. Observations:                 400   AIC:                             3021.
Df Residuals:                     380   BIC:                             3100.
Df Model:                          19
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0001   9.99e-05      1.435      0.152    -5.3e-05       0.000
x2            -2.8515      0.700     -4.073      0.000      -4.228      -1.475
x3            -0.5369      0.501     -1.073      0.284      -1.521       0.447
x4            -0.3550      0.260     -1.365      0.173      -0.866       0.156
x5             0.1941      0.123      1.572      0.117      -0.049       0.437
x6            -0.6570      1.210     -0.543      0.587      -3.036       1.722
x7          2.594e-06      0.000      0.026      0.980      -0.000       0.000
x8          6.681e-06   3.51e-05      0.190      0.849   -6.24e-05    7.58e-05
x9            -0.0458      0.018     -2.534      0.012      -0.081      -0.010
x10            0.0456      0.018      2.528      0.012       0.010       0.081
x11            0.0004      0.000      1.174      0.241      -0.000       0.001
x12         2.471e-05   3.84e-05      0.644      0.520   -5.08e-05       0.000
x13           -0.0004      0.000     -1.683      0.093      -0.001    5.98e-05
x14           -0.0006      0.002     -0.239      0.811      -0.006       0.004
x15            0.0671      0.017      3.882      0.000       0.033       0.101
x16            0.2502      0.037      6.742      0.000       0.177       0.323
x17          -10.3242      9.213     -1.121      0.263     -28.439       7.790
x18          -12.3028      9.438     -1.304      0.193     -30.860       6.255
x19          -11.3802      9.848     -1.156      0.249     -30.743       7.982
x20          -18.1540     10.390     -1.747      0.081     -38.584       2.276
==============================================================================
Omnibus:                      241.659   Durbin-Watson:                   2.113
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4980.344
Skew:                           2.139   Prob(JB):                         0.00
Kurtosis:                      19.749   Cond. No.                     5.03e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.03e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [30]:
predictions = est1.predict(x_test)

In [31]:
from sklearn.metrics import mean_squared_error as MSE

mse = MSE(y_test,predictions)

mse

41.84628255071284

Provide an explanation of the OLS regression results. In particular, briefly explain and interpret: 

- R-squared, 

- coeff, 

Finally, 

- which are the statistically significant predictors and why? 

**(1 pt)**

R-squared: is to describe your data can predict the variable to what extent. if R = 1, means your data can predict the y variable precisely(100%)    
coeff: the coeff of xi means the influence of xi on y. The greater the coeff, the greater xi will influence y.

x2,x14,x15,x16 are the statistically significant predictors, beacause their P value is less than 0.05 which means we can believe these factors have linear relationship with y.

### Task 3

We will attempt to improve the MSE. In order to do so we are going to use regularization by returning a regularized fit to the linear regression model. Note that regularization's goal is to reduce overfitting, that is it creates a more generalized linear model and removes possible noise from the dataset. You will complete this task by using the .fit_regularized() method, and more specifically the **ridge fit**. More details can be found [here](http://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.OLS.fit_regularized.html). Perform Kfold cross-validation, where K = 5, to both the linear model and the regularized linear model, in order to decide which performs better. Report the MSE of the two models. Remember to shuffle the data before performing cross-validation. **(2 pt)**

In [33]:
est2 = est.fit_regularized(alpha = 0, L1_wt = 0)

predictions2 = est2.predict(x_test)

mse2 = MSE(y_test,predictions2)

mse2

41.846282550712814

In [36]:
from sklearn.utils import shuffle
import sklearn.model_selection as model_selection
from sklearn.model_selection import KFold


kf = KFold(n_splits = 5, shuffle = True)

mean_mse = 0


for train_index, test_index in kf.split(X):
    
    #print("TRAIN:", train_index, "TEST:", test_index)
    
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    est9 = sm.OLS(y_train,X_train)
    est9 = est9.fit()
    
    pre = est9.predict(X_test)
    mean_mse += MSE(y_test,pre)
    
#x_tra, x_te, y_tra, y_te = model_selection.train_test_split(X1, Y1, test_size=0.2, random_state=0)

print("The MSE of the linear model is :",mean_mse/5)

The MSE of the linear model is : 209.28889402312544

In [37]:
kf = KFold(n_splits = 5, shuffle = True)

mean_mse = 0


for train_index, test_index in kf.split(X):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    est9 = sm.OLS(y_train,X_train)
    est9 = est9.fit_regularized(alpha = 0.2, L1_wt = 0)
    #print(est9.summary())
    
    pre = est9.predict(X_test)
    mean_mse += MSE(y_test,pre)
    
#x_tra, x_te, y_tra, y_te = model_selection.train_test_split(X1, Y1, test_size=0.2, random_state=0)

print("The MSE of the regularized linear model is :",mean_mse/5)

The MSE of the regularized linear model is : 165.2294280910444

Try the following values for the ridge regression parameter $\alpha$ (the penalty weight), $\alpha = [0,5,10,100]$.**(1 pt)**

In [38]:
def cal_mse_with_different_a(a):

    kf = KFold(n_splits = 5, shuffle = True)

    mean_mse = 0


    for train_index, test_index in kf.split(X):
        #print("TRAIN:", train_index, "TEST:", test_index)
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = Y[train_index], Y[test_index]
        est9 = sm.OLS(y_train,X_train)
        est9 = est9.fit_regularized(alpha = a, L1_wt = 0)
        #print(est9.summary())

        pre = est9.predict(X_test)
        mean_mse += MSE(y_test,pre)

    #x_tra, x_te, y_tra, y_te = model_selection.train_test_split(X1, Y1, test_size=0.2, random_state=0)

    print("The MSE of the regularized linear model with alpha = ", a, " is :",mean_mse/5)

In [39]:
def ori_cal_mse():
    kf = KFold(n_splits = 5, shuffle = True)

    mean_mse = 0


    for train_index, test_index in kf.split(X):
        #print("TRAIN:", train_index, "TEST:", test_index)
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = Y[train_index], Y[test_index]
        est9 = sm.OLS(y_train,X_train)
        est9 = est9.fit()
        #print(est9.summary())

        pre = est9.predict(X_test)
        mean_mse += MSE(y_test,pre)

    #x_tra, x_te, y_tra, y_te = model_selection.train_test_split(X1, Y1, test_size=0.2, random_state=0)

    print("The MSE of the linear model is :",mean_mse/5)

In [40]:
for a in [0,5,10,100]:
    cal_mse_with_different_a(a)

The MSE of the regularized linear model with alpha =  0  is : 204.45689292047004
The MSE of the regularized linear model with alpha =  5  is : 164.14182966901177
The MSE of the regularized linear model with alpha =  10  is : 184.76589075559338
The MSE of the regularized linear model with alpha =  100  is : 263.7056014196586

Based on your knowledge and your results, as a data scientist would you prefer a linear model, or a regularized linear model? What effects can a zero (or very small) $\alpha$ and a very large $\alpha$ cause?**(1 pt)**

I prefer a regularized linear model.Because it reduces overfitting
If the $\alpha$ = 0 ,it means the model is just an ordinary least squares regression.
So, the larger is the $\alpha$, the higher is the smoothness constraint

### Task 4

Another way that may help us improve the MSE is by adding quadratic terms of significant variables in the model. Add 2 quadratic terms in your **regularized linear model** based on two significant variables. An interesting and intuitive tutorial about understanding which are the significant variables and the importance of quadratic terms can be found [here](http://statisticsbyjim.com/regression/interpret-coefficients-p-values-regression/). Note that in order to add the quadratic terms you will need to change the formula of your model, as in [example](http://www.statsmodels.org/dev/examples/notebooks/generated/formulas.html) and in [example](https://stackoverflow.com/questions/31978948/python-stats-models-quadratic-term-in-regression/36539157). Perform Kfold cross-validation, where K = 5, to both the linear model and the regularized linear model with quadratic terms, in order to decide which performs better. Report the MSE of the two models. Remember to shuffle the data before performing cross-validation. **(2 pt)**

In [57]:
from statsmodels.formula.api import ols
data = df3

data['like2'] = data.like **2 
data['Category2'] = data.Category **2



cal_mse_with_different_a(0)
ori_cal_mse()

The MSE of the regularized linear model with alpha =  0  is : 251.58406696350318
The MSE of the linear model is : 243.84192803297833

What issues do you think could come up if we used too many quadratic or cubic terms in our model?**(1 pt)**

The linear model will more likely to become a polynomial model